# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

## homepage slider
arche_api_topcollections:
  path: '/api/topcollections/{count}/{lang}'
  controller: 'App\Controller\MetadataController::getTopCollections'
  requirements:
    count: '^[^\?]*$'
    lang: '^[^\?]*$'
    _permission: 'access content'
    _access: 'TRUE'
    
## metadata view main api    
arche_core_api_expert:    
  path: '/api/expert/{id}/{lang}'
  defaults:
    _controller: 'App\Controller\MetadataController::getExpertData'
  requirements:
    id: '^[^\?]*$'
    lang: '^[^\?]*$'
    _permission: 'access content'
    _access: 'TRUE'     

## breadrcumb
arche_core_api_breadcrumb:    
  path: '/api/breadcrumb/{id}/{lang}'
  defaults:
    _controller: 'App\Controller\MetadataController::getBreadcrumb'
  requirements:
    id: '^[^\?]*$'
    lang: '^[^\?]*$'
    _permission: 'access content'
    _access: 'TRUE'  
    
## metadata view child api
arche_core_api_child_tree:    
    path: '/api/child-tree/{id}/{lang}'
    defaults:
        _controller: '\App\Controller\ChildController::getChildTreeData'
    requirements:
        identifier: '^[^\?]*$'
        lang: '^[^\?]*$'
        _permission: 'access content'
        _access: 'TRUE'


## metadata view facets
arche_core_api_versions_list:    
    path: '/api/versions-list/{id}/{lang}'
    defaults:
        _controller: '\App\Controller\VersionsController::getVersionsList'
    requirements:
        identifier: '^[^\?]*$'
        lang: '^[^\?]*$'
        _permission: 'access content'
        _access: 'TRUE'            



## metadata datatables
arche_core_api_rpr_table:    
    path: '/api/rprDT/{id}/{lang}'
    defaults:
        _controller: '\App\Controller\InverseDataController::getRPRDT'
    requirements:
        identifier: '^[^\?]*$'
        lang: '^[^\?]*$'
        _permission: 'access content'
        _access: 'TRUE'         
      
arche_core_api_publications_table:    
    path: '/api/publicationsDT/{id}/{lang}'
    defaults:
        _controller: '\App\Controller\InverseDataController::getPublicationsDT'
    requirements:
        identifier: '^[^\?]*$'
        lang: '^[^\?]*$'
        _permission: 'access content'
        _access: 'TRUE'    
        
arche_core_api_collectionConcept_table:    
    path: '/api/collectionConceptDT/{id}/{lang}'
    defaults:
        _controller: '\App\Controller\InverseDataController::getCollectionConceptDT'
    requirements:
        identifier: '^[^\?]*$'
        lang: '^[^\?]*$'
        _permission: 'access content'
        _access: 'TRUE'            
        
arche_core_api_project_accociated_table:    
    path: '/api/projectAssociatedDT/{id}/{lang}'
    defaults:
        _controller: '\App\Controller\InverseDataController::getProjectAssociatedDT'
    requirements:
        identifier: '^[^\?]*$'
        lang: '^[^\?]*$'
        _permission: 'access content'
        _access: 'TRUE'            
        
        
        
        